<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAUfbgdU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAUfbgdU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAUfbgdU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAUfbgdU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAUfbgdU\App_KernelDevDebugContainer([
    'container.build_hash' => 'AUfbgdU',
    'container.build_id' => '31a9c4a1',
    'container.build_time' => 1639051660,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAUfbgdU');
